# version: "3.8"

services:
  base:
    build:
      context: .
      dockerfile: dockerfile.base
    image: historical-archive-base:latest

  # The main web application service
  webapp:
    build:
      context: .
      dockerfile: dockerfile.app
    depends_on:
      - base
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./src/app/static/images:/app/src/app/static/images
      - ./src/app/vital_records_index:/app/src/app/vital_records_index

    command: python src/app/app.py

  # A dedicated worker for heavy OCR tasks
  ocr-worker:
    build:
      context: .
      dockerfile: dockerfile.worker
    depends_on:
      - base
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: ["sleep", "infinity"]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all # Make GPU available to container
