FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libglx-mesa0 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libgomp1 \
    ffmpeg \
    curl \
    && rm -rf /var/lib/apt/lists/*

# minimal requirements
COPY requirements.txt .
COPY ../../src/utils.py /app/
COPY ../../src/genealogy/ /app/genealogy/

RUN pip install --no-cache-dir -r requirements.txt

COPY ../../src/app/ /app/app/
COPY ../data /app/data/

EXPOSE 5000
CMD ["python", "app/app.py"]