apiVersion: v1
kind: Service
metadata:
  name: ocr-app-service
  namespace: historical-ocr
  labels:
    app: ocr-app
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: ocr-app
